[package]
name = "iar-swarm-formigas"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
piston = "1.0.0"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.85.0"
uuid = { version = "1.9.1", features = ["v4"] }